name = "actions"
name_pretty = "Actions"
icon = "action"

[[entries]]
text = "Themes"
icon = "preferences-color-symbolic"
actions = { "toggle" = "walker --provider menus:themes" }

[[entries]]
text = "Reboot"
icon = "system-reboot-symbolic"
actions = { "toggle" = "systemctl reboot" }

[[entries]]
text = "Shutdown"
icon = "system-shutdown-symbolic"
actions = { "toggle" = "systemctl poweroff" }

