name = "themes"
name_pretty = "Themes"
icon = "style"

[[entries]]
text = "catppuccin"
actions = { "toggle" = "~/.local/bin/set_theme catppuccin" }

[[entries]]
text = "rose-pine"
actions = { "toggle" = "~/.local/bin/set_theme rose-pine" }

[[entries]]
text = "tokyo-night"
actions = { "toggle" = "~/.local/bin/set_theme tokyo-night" }

